external_components:
  - source:
      type: local
      path: external_components  # Sin barras laterales, solo el nombre de la carpeta
    components: [ tmp300a ]      # Forzamos la carga del componente

uart:
  id: uart_bus
  baud_rate: 9600
  rx_pin: GPIO33


sensor:
# Sensor TPM-300A 2.2
  - platform: tmp300a
    update_interval: 3s
    voc:
      name: "VOC"
      icon: "mdi:air-filter"
      unit_of_measurement: "PPM"
      filters:
        - calibrate_linear:
            # Mapeo: (Valor que entra -> Valor que querés ver)
            - 0.0 -> 400.0
            - 2000.0 -> 5000.0
    eco2:
      name: "eCO2"
    lpg:
      name: "LPG"






